org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.43-beta

## Mod Properties

mod_id=luminax
mod_name=Luminax
mod_license=LGPLv3
mod_version=2.0.0
mod_group_id=dev.satherov.luminax

## Dependecies

sathlib_version=1.0.1
jei_version=29.5.0.26